apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: catalog-frontend-deploy

parameters:
- name: NAME
  description: Application name
  value: catalog-ui

- name: FRONTEND_URL
  description: Public route hostname

objects:

# Deployment
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${NAME}

  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ${NAME}

    template:
      metadata:
        labels:
          app: ${NAME}

      spec:
        containers:
        - name: ${NAME}
          image: image-registry.openshift-image-registry.svc:5000/petrol/${NAME}:latest
          ports:
          - containerPort: 8080

---
# Service
- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}

  spec:
    selector:
      app: ${NAME}
    ports:
    - port: 8080
      targetPort: 8080

---
# Route
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: ${NAME}

  spec:
    host: ${FRONTEND_URL}
    to:
      kind: Service
      name: ${NAME}
    port:
      targetPort: 8080
    tls:
      termination: edge
